
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-idp-ss-sso-secret
  namespace: crossplane-system
  labels:
    entity: ssint
    env: main
    capability: access
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
type: Opaque
stringData:
  client_secret: ""

---
apiVersion: zero.upjet-cloudflare.upbound.io/v1alpha1
kind: TrustAccessIdentityProvider
metadata:
  name: cloudflare-idp-ss-sso
  labels:
    entity: ssint
    env: main
    capability: access
spec:
  forProvider:
    accountId: ed503c805407090970caf579da8193a8
    name: SS SSO
    type: google-apps
    config:
      appsDomain: "simplesalt.company"
      clientId: "358340479202-r0acjnd0au5r9l963kjlr6n0ccshav4j.apps.googleusercontent.com"
      clientSecretSecretRef:
        name: cloudflare-idp-ss-sso-secret
        namespace: crossplane-system
        key: client_secret
      pkceEnabled: true
    scimConfig:
      enabled: true
      userDeprovision: true
      seatDeprovision: true
      identityUpdateBehavior: "no_action"
  providerConfigRef:
    kind: ProviderConfig
    name: default
