
---
apiVersion: zero.upjet-cloudflare.upbound.io/v1alpha1
kind: TrustOrganization
metadata:
  annotations:
    crossplane.io/external-name: ba92fe12c6c1275f965c7c86e3b392ac
  name: cf-main-zero-trust-org
  labels:
    entity: ssint
    env: main
    capability: access
spec:
  forProvider:
    accountId: ba92fe12c6c1275f965c7c86e3b392ac
    authDomain: fqurzlaaagt.cloudflareaccess.com
    name: fqurzlaaagt.cloudflareaccess.com
    allowAuthenticateViaWarp: false
    denyUnmatchedRequests: false
  providerConfigRef:
    name: ssint-main

---

---
apiVersion: v1
kind: Secret
metadata:
  name: ssint-main-g-idp-id
  namespace: flux-system
  labels:
    entity: ssint
    env: main
    capability: access
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
type: Opaque

---
apiVersion: v1
kind: Secret
metadata:
  name: ssint-main-g-idp-secret
  namespace: crossplane-system
  labels:
    entity: ssint
    env: main
    capability: access
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
type: Opaque

---
apiVersion: zero.upjet-cloudflare.upbound.io/v1alpha1
kind: TrustAccessIdentityProvider
metadata:
  name: cf-main-idp-ssint-sso
  labels:
    entity: ssint
    env: main
    capability: access
spec:
  forProvider:
    accountId: ba92fe12c6c1275f965c7c86e3b392ac
    name: SS SSO
    type: google-apps
    config:
      appsDomain: simplesalt.company
      clientId: "${client_id}"
      clientSecretSecretRef:
        name: ssint-main-g-idp-secret
        namespace: crossplane-system
        key: client_secret
      pkceEnabled: true
    scimConfig:
      enabled: false
  providerConfigRef:
    name: ssint-main

---

---
apiVersion: zero.upjet-cloudflare.upbound.io/v1alpha1
kind: TrustAccessPolicy
metadata:
  name: simplesalt-email-domain
  annotations:
    crossplane.io/external-name: "79bac8d3-6c82-4ac5-bbdb-f98a3388236c"
  labels:
    entity: ssint
    env: main
    capability: access
spec:
  forProvider:
    accountId: ba92fe12c6c1275f965c7c86e3b392ac
    name: simplesalt.company Email Domain
    decision: allow
    include:
      - emailDomain:
          domain: simplesalt.company
  providerConfigRef:
    name: ssint-main

---
apiVersion: zero.upjet-cloudflare.upbound.io/v1alpha1
kind: TrustAccessApplication
metadata:
  name: cloudflare-app-appflowy-main
  labels:
    entity: ssint
    env: main
    capability: access
spec:
  deletionPolicy: Orphan
  forProvider:
    accountId: ba92fe12c6c1275f965c7c86e3b392ac
    name: appflowy-main
    type: self_hosted
    destinations:
      - type: public
        uri: info.simplesalt.company
    sessionDuration: 24h
    autoRedirectToIdentity: true
    allowedIdps:
      - 42cbdc64-699e-4e17-b470-fb7cda3c0791
    policies:
      - id: 79bac8d3-6c82-4ac5-bbdb-f98a3388236c
        precedence: 1
  providerConfigRef:
    name: ssint-main

---
apiVersion: zero.upjet-cloudflare.upbound.io/v1alpha1
kind: TrustTunnelCloudflaredConfig
metadata:
  name: ssint-main-tunnel-config
  labels:
    entity: ssint
    env: main
    capability: access
spec:
  forProvider:
    accountId: ba92fe12c6c1275f965c7c86e3b392ac
    tunnelId: "83c27a64-4074-474c-9a8f-19448d1c2081"
    config:
      ingress:
        - hostname: info.simplesalt.company
          service: http://big-agi.ssint-main-ai.svc.k.famevans.win:3000
        - service: http_status:404
  providerConfigRef:
    name: ssint-main

---
apiVersion: dns.upjet-cloudflare.upbound.io/v1alpha1
kind: Record
metadata:
  name: info-simplesalt-company
  labels:
    entity: ssint
    env: main
    capability: access
spec:
  forProvider:
    zoneId: 260b251cdb53f8376875a8eb8d03ca0b
    name: info
    type: CNAME
    content: 83c27a64-4074-474c-9a8f-19448d1c2081.cfargotunnel.com
    proxied: true
    ttl: 1
  providerConfigRef:
    name: ssint-main
