apiVersion: v1
kind: Secret
metadata:
  name: gbrain-reranker-secret
  namespace: ssint-main-ai
  labels:
    entity: ssint
    env: main
    capability: ai
  annotations:
    kustomize.toolkit.fluxcd.io/ssa: merge
type: Opaque
