---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: hindsight-main
  namespace: flux-system
  labels:
    entity: ssint
    env: main
    capability: ai
spec:
  interval: 12h
  url: oci://ghcr.io/simplesalt/charts/hindsight
  ref:
    tag: "0.2.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hindsight-main
  namespace: flux-system
  labels:
    entity: ssint
    env: main
    capability: ai
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: hindsight-main
    namespace: flux-system
  targetNamespace: ssint-main-ai
  install:
    createNamespace: false
    timeout: 10m
  values:
    image:
      digest: "sha256:7c069db2d7aeeae82d3d3917292b87b14d6547f979c8b1335a42c94d09d57213"
